#!/usr/bin/env bash
set -euo pipefail

# Single database: the image already created $POSTGRES_DB
: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"

# Fixed schema/user names (no customization)
KEYCLOAK_DB_SCHEMA="keycloak"
KEYCLOAK_DB_USER="keycloak"

MICADO_DB_SCHEMA="micado"
MICADO_DB_USER="micado"

GITEA_DB_SCHEMA="gitea"
GITEA_DB_USER="gitea"

WEBLATE_DB_SCHEMA="weblate"
WEBLATE_DB_USER="weblate"

DBOS_DB_SCHEMA="dbos"
DBOS_DB_USER="dbos"

# Only passwords are configurable
: "${KEYCLOAK_DB_PASSWORD:?KEYCLOAK_DB_PASSWORD is required}"
: "${MICADO_APP_PASSWORD:?MICADO_APP_PASSWORD is required}"
: "${GITEA_DB_PASSWORD:?GITEA_DB_PASSWORD is required}"
: "${WEBLATE_DB_PASSWORD:?WEBLATE_DB_PASSWORD is required}"

psql_main() {
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" "$@"
}

echo "[initdb] Hardening public schema..."
psql_main <<'EOSQL'
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
EOSQL

echo "[initdb] Creating roles (or updating passwords)..."
psql_main <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${KEYCLOAK_DB_USER}') THEN
    CREATE ROLE ${KEYCLOAK_DB_USER} LOGIN ENCRYPTED PASSWORD '${KEYCLOAK_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${KEYCLOAK_DB_USER} WITH LOGIN ENCRYPTED PASSWORD '${KEYCLOAK_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${MICADO_DB_USER}') THEN
    CREATE ROLE ${MICADO_DB_USER} LOGIN ENCRYPTED PASSWORD '${MICADO_APP_PASSWORD}';
  ELSE
    ALTER ROLE ${MICADO_DB_USER} WITH LOGIN ENCRYPTED PASSWORD '${MICADO_APP_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${GITEA_DB_USER}') THEN
    CREATE ROLE ${GITEA_DB_USER} LOGIN ENCRYPTED PASSWORD '${GITEA_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${GITEA_DB_USER} WITH LOGIN ENCRYPTED PASSWORD '${GITEA_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${WEBLATE_DB_USER}') THEN
    CREATE ROLE ${WEBLATE_DB_USER} LOGIN ENCRYPTED PASSWORD '${WEBLATE_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${WEBLATE_DB_USER} WITH LOGIN ENCRYPTED PASSWORD '${WEBLATE_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DBOS_DB_USER}') THEN
    CREATE ROLE ${DBOS_DB_USER} LOGIN ENCRYPTED PASSWORD '${MICADO_APP_PASSWORD}';
  ELSE
    ALTER ROLE ${DBOS_DB_USER} WITH LOGIN ENCRYPTED PASSWORD '${MICADO_APP_PASSWORD}';
  END IF;
END
\$\$;
EOSQL

echo "[initdb] Creating schemas and granting privileges..."
psql_main <<EOSQL
-- Create schemas owned by their service user
CREATE SCHEMA IF NOT EXISTS ${KEYCLOAK_DB_SCHEMA} AUTHORIZATION ${KEYCLOAK_DB_USER};
CREATE SCHEMA IF NOT EXISTS ${MICADO_DB_SCHEMA} AUTHORIZATION ${MICADO_DB_USER};
CREATE SCHEMA IF NOT EXISTS ${GITEA_DB_SCHEMA} AUTHORIZATION ${GITEA_DB_USER};
CREATE SCHEMA IF NOT EXISTS ${WEBLATE_DB_SCHEMA} AUTHORIZATION ${WEBLATE_DB_USER};
CREATE SCHEMA IF NOT EXISTS ${DBOS_DB_SCHEMA} AUTHORIZATION ${DBOS_DB_USER};

-- Allow each service user to connect to the single DB
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${KEYCLOAK_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${MICADO_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${GITEA_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${WEBLATE_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DBOS_DB_USER};

-- Schema usage/create
GRANT USAGE, CREATE ON SCHEMA ${KEYCLOAK_DB_SCHEMA} TO ${KEYCLOAK_DB_USER};
GRANT USAGE, CREATE ON SCHEMA ${MICADO_DB_SCHEMA} TO ${MICADO_DB_USER};
GRANT USAGE, CREATE ON SCHEMA ${GITEA_DB_SCHEMA} TO ${GITEA_DB_USER};
GRANT USAGE, CREATE ON SCHEMA ${WEBLATE_DB_SCHEMA} TO ${WEBLATE_DB_USER};
GRANT USAGE, CREATE ON SCHEMA ${DBOS_DB_SCHEMA} TO ${DBOS_DB_USER};

-- Many extensions/functions remain in public; allow USAGE (but not CREATE)
GRANT USAGE ON SCHEMA public TO ${KEYCLOAK_DB_USER};
GRANT USAGE ON SCHEMA public TO ${MICADO_DB_USER};
GRANT USAGE ON SCHEMA public TO ${GITEA_DB_USER};
GRANT USAGE ON SCHEMA public TO ${WEBLATE_DB_USER};
GRANT USAGE ON SCHEMA public TO ${DBOS_DB_USER};

GRANT ALL PRIVILEGES ON SCHEMA ${KEYCLOAK_DB_SCHEMA} TO ${KEYCLOAK_DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA ${DBOS_DB_SCHEMA} TO ${DBOS_DB_USER};
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${DBOS_DB_USER};


-- search_path per role (include public second for extension functions)
ALTER ROLE ${KEYCLOAK_DB_USER} IN DATABASE ${POSTGRES_DB} SET search_path = ${KEYCLOAK_DB_SCHEMA}, public;
ALTER ROLE ${MICADO_DB_USER}   IN DATABASE ${POSTGRES_DB} SET search_path = ${MICADO_DB_SCHEMA}, public;
ALTER ROLE ${GITEA_DB_USER}    IN DATABASE ${POSTGRES_DB} SET search_path = ${GITEA_DB_SCHEMA}, public;
ALTER ROLE ${WEBLATE_DB_USER}  IN DATABASE ${POSTGRES_DB} SET search_path = ${WEBLATE_DB_SCHEMA}, public;
ALTER ROLE ${DBOS_DB_USER}     IN DATABASE ${POSTGRES_DB} SET search_path = ${DBOS_DB_SCHEMA}, public;

-- Default privileges (objects created in that schema by that owner)
ALTER DEFAULT PRIVILEGES FOR ROLE ${KEYCLOAK_DB_USER} IN SCHEMA ${KEYCLOAK_DB_SCHEMA}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${KEYCLOAK_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${KEYCLOAK_DB_USER} IN SCHEMA ${KEYCLOAK_DB_SCHEMA}
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${KEYCLOAK_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${MICADO_DB_USER} IN SCHEMA ${MICADO_DB_SCHEMA}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${MICADO_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${MICADO_DB_USER} IN SCHEMA ${MICADO_DB_SCHEMA}
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${MICADO_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${GITEA_DB_USER} IN SCHEMA ${GITEA_DB_SCHEMA}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${GITEA_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${GITEA_DB_USER} IN SCHEMA ${GITEA_DB_SCHEMA}
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${GITEA_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${WEBLATE_DB_USER} IN SCHEMA ${WEBLATE_DB_SCHEMA}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${WEBLATE_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${WEBLATE_DB_USER} IN SCHEMA ${WEBLATE_DB_SCHEMA}
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${WEBLATE_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${DBOS_DB_USER} IN SCHEMA ${DBOS_DB_SCHEMA}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DBOS_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DBOS_DB_USER} IN SCHEMA ${DBOS_DB_SCHEMA}
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${DBOS_DB_USER};
EOSQL

echo "[initdb] Installing extensions (prefer micado/weblate schemas when supported)..."
psql_main <<EOSQL
-- Helper: try WITH SCHEMA, fallback to default if extension doesn't support it in your build.
DO \$\$
BEGIN
  BEGIN
    EXECUTE format('CREATE EXTENSION IF NOT EXISTS pgroonga WITH SCHEMA %I', '${MICADO_DB_SCHEMA}');
  EXCEPTION WHEN others THEN
    CREATE EXTENSION IF NOT EXISTS pgroonga;
  END;

  BEGIN
    EXECUTE format('CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA %I', '${MICADO_DB_SCHEMA}');
  EXCEPTION WHEN others THEN
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
  END;

  CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

  BEGIN
    EXECUTE format('CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA %I', '${WEBLATE_DB_SCHEMA}');
  EXCEPTION WHEN others THEN
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
  END;

  BEGIN
    EXECUTE format('CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA %I', '${WEBLATE_DB_SCHEMA}');
  EXCEPTION WHEN others THEN
    CREATE EXTENSION IF NOT EXISTS btree_gin;
  END;
END
\$\$;
EOSQL

echo "[initdb] Done."